// seedData.js - Initial Seed Complaints and Users for Kerala Districts
export const defaultUsers = [
  { name: "Ragesh K.", username: "citizen", password: "123", role: "citizen" },
  { name: "Devika S.", username: "devika", password: "123", role: "citizen" },
  { name: "Panchayath Road Admin", username: "panchayath_road", password: "123", role: "PANCHAYATH_ROAD_ADMIN" },
  { name: "Panchayath Health Admin", username: "panchayath_health", password: "123", role: "PANCHAYATH_HEALTH_ADMIN" },
  { name: "District Road Admin", username: "district_road", password: "123", role: "DISTRICT_ROAD_ADMIN" },
  { name: "District Health Admin", username: "district_health", password: "123", role: "DISTRICT_HEALTH_ADMIN" },
  { name: "State Water Admin", username: "state_water", password: "123", role: "STATE_WATER_ADMIN" },
  { name: "State Road Admin", username: "state_road", password: "123", role: "STATE_ROAD_ADMIN" }
];

export const initialComplaints = [
  {
    id: "c1",
    category: "pothole",
    titleEn: "Large pothole in Kondotty center road",
    titleMl: "റോഡിലെ ടാർ ഇളകി വലിയ കുഴികൾ രൂപപ്പെട്ടിരിക്കുന്നു",
    descEn: "A damaged section of a paved road with exposed soil and gravel, obstructing regular vehicular movement.",
    descMl: "കൊണ്ടോട്ടി സെന്റർ റോഡിൽ ടാർ ഇളകി വലിയ കുഴി രൂപപ്പെട്ടിരിക്കുന്നു. വാഹനയാത്രക്കാർക്ക് ഇത് വലിയ അപകടഭീഷണിയാണ്.",
    location: "Kondotty, Malappuram",
    district: "MPM",
    lat: 11.1495,
    lng: 75.9620,
    image: "https://images.unsplash.com/photo-1515162305285-0293e4767cc2?w=800&auto=format&fit=crop&q=80",
    createdAt: Date.now() - 2 * 3600 * 1000, // 2 hours ago
    status: "submitted",
    seriousness: "high",
    originalSeriousness: "high",
    citizen: "Ragesh K.",
    upvotes: 14,
    upvotedBy: ["devika"],
    comments: [
      { id: "cm1", user: "John D.", text: "This has been causing traffic blocks for weeks.", time: "1h ago" },
      { id: "cm2", user: "Aminah", text: "Two-wheelers are slipping here at night. Very dangerous!", time: "45m ago" }
    ]
  },
  {
    id: "c2",
    category: "waste",
    titleEn: "Plastic waste accumulation in Kumbalam water body",
    titleMl: "പൊതു ജലാശയത്തിൽ പ്ലാസ്റ്റിക് മാലിന്യങ്ങളും പായലും",
    descEn: "Plastic waste and algae accumulation in a public water body, causing bad odor and breeding mosquitoes.",
    descMl: "കുമ്പളം കായലോരത്ത് പ്ലാസ്റ്റിക് കുപ്പികളും മാലിന്യങ്ങളും അടിഞ്ഞുകൂടി കിടക്കുന്നു. ഇത് ജലമലിനീകരണത്തിനും പകർച്ചവ്യാധികൾക്കും കാരണമാകുന്നു.",
    location: "Kumbalam, Ernakulam",
    district: "EKM",
    lat: 9.9074,
    lng: 76.3059,
    image: "https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?w=800&auto=format&fit=crop&q=80",
    createdAt: Date.now() - 12 * 24 * 3600 * 1000, // 12 days ago
    status: "resolved",
    seriousness: "medium",
    originalSeriousness: "medium",
    citizen: "Suresh Paul",
    upvotes: 28,
    upvotedBy: ["citizen", "devika"],
    comments: [
      { id: "cm3", user: "John Paul", text: "Reported it and thankfully the municipality cleaned it yesterday!", time: "1d ago" }
    ],
    scheduledDate: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString().split('T')[0],
    resolvedDate: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString().split('T')[0],
    resolutionNotes: "The environmental cleaning department cleared all plastic debris and placed trash cans.",
    resolutionImage: "https://images.unsplash.com/photo-1618477388954-7852f32655ec?w=800&auto=format&fit=crop&q=80"
  },
  {
    id: "c3",
    category: "streetlight",
    titleEn: "Broken streetlight near Paruthippara junction",
    titleMl: "പരുത്തിപ്പാറ ജംഗ്ഷനിലെ തെരുവ് വിളക്ക് കേടാണ്",
    descEn: "Streetlight has been offline for over a week, making the intersection dark and unsafe for pedestrians.",
    descMl: "പരുത്തിപ്പാറ ജംഗ്ഷനിലെ തെരുവ് വിളക്ക് ഒരാഴ്ചയായി കത്തുന്നില്ല. രാത്രികാലങ്ങളിൽ കാൽനടയാത്രക്കാർക്ക് വഴി നടക്കാൻ ബുദ്ധിമുട്ടാണ്.",
    location: "Paruthippara, Thiruvananthapuram",
    district: "TVM",
    lat: 8.5367,
    lng: 76.9427,
    image: "https://images.unsplash.com/photo-1509024640554-6cad6222b07e?w=800&auto=format&fit=crop&q=80",
    createdAt: Date.now() - 8 * 24 * 3600 * 1000, // 8 days ago
    status: "reviewed",
    seriousness: "low",
    originalSeriousness: "low",
    citizen: "Fathima N.",
    upvotes: 9,
    upvotedBy: [],
    comments: []
  },
  {
    id: "c4",
    category: "waterlogging",
    titleEn: "Waterlogging on Cheerachi main road",
    titleMl: "ചീരച്ചി മെയിൻ റോഡിൽ കനത്ത വെള്ളക്കെട്ട്",
    descEn: "A pothole filled with water on a public road, making it impossible to see the depth of the road damage.",
    descMl: "ചീരച്ചി റോഡിലെ വലിയ കുഴികളിൽ വെള്ളം കെട്ടിക്കിടക്കുന്നു. ഓടകൾ അടഞ്ഞതാണ് കാരണം. കുഴികളുടെ ആഴമറിയാതെ വണ്ടികൾ വീഴുന്നു.",
    location: "Cheerachi, Thrissur",
    district: "TSR",
    lat: 10.4950,
    lng: 76.2230,
    image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&auto=format&fit=crop&q=80",
    createdAt: Date.now() - 6 * 24 * 3600 * 1000, // 6 days ago
    status: "reviewed",
    seriousness: "critical",
    originalSeriousness: "critical",
    citizen: "Devika S.",
    upvotes: 42,
    upvotedBy: ["citizen"],
    comments: [
      { id: "cm5", user: "Haris K.", text: "This needs immediate attention before the monsoon intensifies.", time: "5d ago" }
    ]
  },
  {
    id: "c5",
    category: "property",
    titleEn: "Abandoned cable drum obstructing pedestrian path",
    titleMl: "റോഡരികിൽ ഉപേക്ഷിച്ച നിലയിലുള്ള വലിയ കേബിൾ ഡ്രം",
    descEn: "A large cable drum is left on the roadside, obstructing the public path and blocking pedestrian sightlines.",
    descMl: "തൃശ്ശൂർ റൗണ്ടിനടുത്ത് നടപ്പാതയിൽ വലിയ കേബിൾ ഡ്രം ഉപേക്ഷിച്ചിരിക്കുന്നു. ആളുകൾക്ക് നടന്നുപോകാൻ തടസ്സമുണ്ടാക്കുന്നു.",
    location: "Swaraj Round, Thrissur",
    district: "TSR",
    lat: 10.5244,
    lng: 76.2140,
    image: "https://images.unsplash.com/photo-1584467541268-b040f83be3fd?w=800&auto=format&fit=crop&q=80",
    createdAt: Date.now() - 20 * 24 * 3600 * 1000, // 20 days ago
    status: "submitted",
    seriousness: "medium",
    originalSeriousness: "medium",
    citizen: "Gokul Das",
    upvotes: 18,
    upvotedBy: [],
    comments: [
      { id: "cm6", user: "Haris K.", text: "This has been lying here since the roadwork ended. Needs to be removed.", time: "6d ago" }
    ]
  },
  {
    id: "c6",
    category: "pothole",
    titleEn: "Deep crater on Kozhikode Beach Road",
    titleMl: "കോഴിക്കോട് ബീച്ച് റോഡിലെ വലിയ കുഴി",
    descEn: "A deep crater-like pothole has formed near the beach walkway, posing risks to high traffic on weekends.",
    descMl: "ബീച്ച് റോഡിൽ നടപ്പാതയ്ക്ക് സമീപം വലിയ ആഴമുള്ള കുഴി രൂപപ്പെട്ടിരിക്കുന്നു. അവധി ദിവസങ്ങളിൽ വൻ തിരക്കുള്ള ഈ ഭാഗത്ത് ഇത് അപകടമുണ്ടാക്കാം.",
    location: "Beach Road, Kozhikode",
    district: "KKD",
    lat: 11.2588,
    lng: 75.7690,
    image: "https://images.unsplash.com/photo-1621293954908-907141467fc7?w=800&auto=format&fit=crop&q=80",
    createdAt: Date.now() - 1 * 24 * 3600 * 1000, // 1 day ago
    status: "submitted",
    seriousness: "high",
    originalSeriousness: "high",
    citizen: "Siddharth B.",
    upvotes: 35,
    upvotedBy: ["devika"],
    comments: [
      { id: "cm7", user: "Anil Kumar", text: "I hit this pothole yesterday. Thankfully my bike was okay.", time: "18h ago" }
    ]
  },
  {
    id: "c7",
    category: "waste",
    titleEn: "Indiscriminate garbage dumping in Palakkad canal",
    titleMl: "കനാൽ തീരത്ത് പ്ലാസ്റ്റിക്കും മാലിന്യങ്ങളും തള്ളുന്നു",
    descEn: "Massive pile of domestic trash dumped illegally by the canal banks, blocking seasonal water flow.",
    descMl: "പാലക്കാട് കനാൽ തീരങ്ങളിൽ തദ്ദേശീയമായി പ്ലാസ്റ്റിക് കവറുകളും ഭക്ഷണാവശിഷ്ടങ്ങളും വ്യാപകമായി തള്ളുന്നു. ജലപ്രവാഹം തടസ്സപ്പെടാൻ സാധ്യതയുണ്ട്.",
    location: "Canal Side Road, Palakkad",
    district: "PKD",
    lat: 10.7749,
    lng: 76.6548,
    image: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=800&auto=format&fit=crop&q=80",
    createdAt: Date.now() - 4 * 24 * 3600 * 1000, // 4 days ago
    status: "submitted",
    seriousness: "medium",
    originalSeriousness: "medium",
    citizen: "Anjali Menon",
    upvotes: 22,
    upvotedBy: ["citizen"],
    comments: []
  },
  {
    id: "c8",
    category: "waterlogging",
    titleEn: "Waterlogging at Alappuzha town residential streets",
    titleMl: "ആലപ്പുഴ റെസിഡൻഷ്യൽ ഏരിയയിൽ കനത്ത ജലക്കെട്ട്",
    descEn: "Stagnant stormwater on the roads after a single downpour, flooding gates and entering car parks.",
    descMl: "ശക്തമായ പെയ്ത മഴയെത്തുടർന്ന് റോഡിൽ കെട്ടിക്കിടക്കുന്ന വെള്ളം ഗേറ്റുകൾക്ക് മുകളിലേക്ക് ഉയരുന്നു. അഴുക്കുചാലുകളുടെ നിർമ്മാണം അപര്യാപ്തമാണ്.",
    location: "Vazhicherry Round, Alappuzha",
    district: "ALP",
    lat: 9.4981,
    lng: 76.3388,
    image: "https://images.unsplash.com/photo-1485613961133-4a690377e089?w=800&auto=format&fit=crop&q=80",
    createdAt: Date.now() - 9 * 24 * 3600 * 1000, // 9 days ago
    status: "reviewed",
    seriousness: "high",
    originalSeriousness: "high",
    citizen: "Sandeep V.",
    upvotes: 12,
    upvotedBy: [],
    comments: [
      { id: "cm8", user: "Ragesh K.", text: "This area gets flooded every single season. Proper drain needed.", time: "2d ago" }
    ]
  },
  {
    id: "c9",
    category: "streetlight",
    titleEn: "Streetlight failure near Kakkanad IT Expressway",
    titleMl: "കാക്കനാട് ഇൻഫോപാർക്ക് റോഡിൽ തെരുവ് വിളക്കുകൾ കത്തുന്നില്ല",
    descEn: "A series of 4 streetlights are dark on a blind curve leading to Infopark entrance, causing heavy risk to riders.",
    descMl: "ഇൻഫോപാർക്കിലേക്ക് തിരിയുന്ന കൊടുംവളവിലെ 4 തെരുവ് വിളക്കുകൾ ആഴ്ചകളായി കത്തുന്നില്ല. ഇരുചക്ര വാഹനയാത്രക്കാർ വലിയ ബുദ്ധിമുട്ടിലാണ്.",
    location: "Infopark Road, Kakkanad",
    district: "EKM",
    lat: 10.0159,
    lng: 76.3419,
    image: "https://images.unsplash.com/photo-1543224494-a624d36f7f34?w=800&auto=format&fit=crop&q=80",
    createdAt: Date.now() - 3 * 24 * 3600 * 1000, // 3 days ago
    status: "submitted",
    seriousness: "low",
    originalSeriousness: "low",
    citizen: "Nirmal George",
    upvotes: 6,
    upvotedBy: [],
    comments: []
  },
  {
    id: "c10",
    category: "property",
    titleEn: "Concrete structural block obstructing Trivandrum walkway",
    titleMl: "തിരുവനന്തപുരം വഴുതക്കാട് കാൽനടപ്പാതയിൽ കോൺക്രീറ്റ് കട്ടകൾ",
    descEn: "Unused concrete blocks left behind on the sidewalk from drainage reconstruction, blocking baby strollers.",
    descMl: "ഓടകളുടെ അറ്റകുറ്റപ്പണികൾ കഴിഞ്ഞതിന് ശേഷവും കോൺക്രീറ്റ് കട്ടകൾ നടപ്പാതയിൽ ഉപേക്ഷിച്ചിരിക്കുന്നു. കാൽനടയാത്രക്കാർക്ക് നടക്കാൻ കഴിയില്ല.",
    location: "Vazhuthacaud, Thiruvananthapuram",
    district: "TVM",
    lat: 8.4998,
    lng: 76.9602,
    image: "https://images.unsplash.com/photo-1584467541268-b040f83be3fd?w=800&auto=format&fit=crop&q=80",
    createdAt: Date.now() - 17 * 24 * 3600 * 1000, // 17 days ago
    status: "submitted",
    seriousness: "medium",
    originalSeriousness: "medium",
    citizen: "Gauri Nair",
    upvotes: 19,
    upvotedBy: ["devika"],
    comments: []
  },
  {
    id: "c11",
    category: "pothole",
    titleEn: "Severe pothole in Kondotty central street",
    titleMl: "കൊണ്ടോട്ടി സെന്ററിൽ വലിയ റോഡ് തകരാർ",
    descEn: "Potholes on the paved road at Kondotty center with loose gravel, obstructing regular traffic and vehicle movement.",
    descMl: "കൊണ്ടോട്ടി സെന്റർ റോഡിൽ വലിയ കുഴി രൂപപ്പെട്ടിരിക്കുന്നു. വലിയ വാഹനാപകടങ്ങൾക്ക് സാധ്യതയുള്ളതിനാൽ ഇത് പരിഹരിക്കണം.",
    location: "Kondotty, Malappuram",
    district: "MPM",
    lat: 11.1499,
    lng: 75.9625,
    image: "https://images.unsplash.com/photo-1515162305285-0293e4767cc2?w=800&auto=format&fit=crop&q=80",
    createdAt: Date.now() - 1 * 3600 * 1000,
    status: "submitted",
    seriousness: "medium",
    originalSeriousness: "medium",
    citizen: "Amal Jin",
    upvotes: 8,
    upvotedBy: [],
    comments: []
  },
  {
    id: "c12",
    category: "pothole",
    titleEn: "Crater formed near Kozhikode Beach walkway",
    titleMl: "കോഴിക്കോട് ബീച്ച് വാക്ക് വേയ്ക്ക് സമീപം കുഴി",
    descEn: "A deep pothole has opened near the Kozhikode beach walkway, posing serious risks to vehicles and pedestrians.",
    descMl: "കോഴിക്കോട് ബീച്ച് വാക്ക് വേയ്ക്ക് സമീപം വലിയ കുഴി രൂപപ്പെട്ടിരിക്കുന്നു. കാൽനടക്കാർക്കും രാത്രി യാത്രക്കാർക്കും ഭീഷണിയാണ്.",
    location: "Beach Road, Kozhikode",
    district: "KKD",
    lat: 11.2591,
    lng: 75.7693,
    image: "https://images.unsplash.com/photo-1621293954908-907141467fc7?w=800&auto=format&fit=crop&q=80",
    createdAt: Date.now() - 6 * 3600 * 1000,
    status: "submitted",
    seriousness: "medium",
    originalSeriousness: "medium",
    citizen: "Deepak Parol",
    upvotes: 12,
    upvotedBy: [],
    comments: []
  }
];
